### PR TITLE
Sticky position has 1px off the top

### PR DESCRIPTION
**Pull request by stanislav-slavov**
The issue occurs on Chrome.

### CODE REVIEW

**Comment by stanislav-slavov** [comment]
> This change looks super unobvious. Is it a Chrome bug?

Yes. It doesn't occur on Firefox.

**Comment by davidyuk** [comment]
This issue should be investigated in detail. Probably it is because of overcomplicated markup.

**Comment by davidyuk** [comment]
@stanislav-slavov for me this issue fixes after removing of this line: https://github.com/aeternity/superhero-ui/blob/cfd50e9545a63a15e205d88b3956b391452028a3/src/views/TipsList.vue#L99
what is the purpose of it?

**Comment by stanislav-slavov** [comment]
> @stanislav-slavov for me this issue fixes after removing of this line:
> 
> https://github.com/aeternity/superhero-ui/blob/cfd50e9545a63a15e205d88b3956b391452028a3/src/views/TipsList.vue#L99
> 
> 
> what is the purpose of it?

The issue still persists and occurs on other pages with the mobile navigation where this style is not present. 
This line seems redundant.

**Pull request merged**
