### PR TITLE
Added Cover photo, activity section, location, balance

### PR DESCRIPTION
**Pull request by stanislav-slavov**

### CODE REVIEW

**Comment by mradkov** [comment]
Is this still draft @stanislav-slavov ?

**Comment by stanislav-slavov** [comment]
> Is this still draft @stanislav-slavov ?

The part with the user profile updates is finished and ready for review, but I have also added pin menus and filters in the front-end. These are still placeholders until the services are done in the back-end and bound to work in the ui.

If we want to review and merge the part with the profile we could hide the pin functionality for now and finish it later or keep this as a draft and merge the whole thing when ready.

**Comment by mradkov** [comment]
> > Is this still draft @stanislav-slavov ?
> 
> The part with the user profile updates is finished and ready for review, but I have also added pin menus and filters in the front-end. These are still placeholders until the services are done in the back-end and bound to work in the ui.
> 
> If we want to review and merge the part with the profile we could hide the pin functionality for now and finish it later or keep this as a draft and merge the whole thing when ready.

Pinning should be now possible after https://github.com/aeternity/tipping-community-backend/pull/144

**Comment by mradkov** [comment]
Can you also fix #685 in the scope of this PR @stanislav-slavov? Thanks 🙏

**Pull request merged**
