### PR TITLE
WordBazaar - Design adjustments and Search

### LINKED ISSUE #978: WordBazaar - buy/sell steps design

### LINKED ISSUE #979: WordBazaar - voting vote cards design and messages adjustment

### LINKED ISSUE #989: WordBazaar - loading indicator for sort words

### LINKED ISSUE #990: WordBazaar - search for asset

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Closes #978 
Closes #979 
Closes #989 
Closes #990

Step-loader is shown when you buy/sell tokens.
You can add messages, to explain why the vote is initiated.
Search functionality for assets.
Loading indicator while the list of assets is fetched.

### CODE REVIEW

**Comment by thepiwo** [comment]
styles seem broken

image
image

**Comment by Liubov-crypto** [comment]
Tested, LGTM

**Review by thepiwo — COMMENTED** [review]
title size is inconsistent depending on page, seems to big for buttons in the header bar 
image

**Review by thepiwo — APPROVED** [review]
very nice work!

**Pull request merged**
