### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by CedrikNikita**
I don't want to fix this [issue](https://github.com/aeternity/superhero-ui/pull/970/commits/e8583fa7b5c5b16569e053f8c61bfe89b3cf4265#diff-e65d3e51412063b61ea75825daeb4e82bc97d7194ff8d33bc8c254ac85886585R1) in that PR.

### CODE REVIEW

**Review by davidyuk — APPROVED** [review]
Json changes look good, but it should be tested after the build is fixed, cc: @Liubov-crypto

**Comment by Liubov-crypto** [comment]
Pin content to channel - pass
Search - pass
Change currency - pass
Account info - pass
Change profile info (Gear button) - failed/ not active 
Comments - pass
Retip - pass (on the mainnet)/ failed (on the testnet) 
Tip on the feed - pass (on the mainnet)/ failed (on the testnet) 
Login with Web Wallet button - failed/not active
Voting - create a new poll - pass
Vote - pass
Revoke vote - pass
Search - pass
Meet - pass
League - pass
FAQ - pass

Btw, when I created a new poll to vote, there was strange behaviour:

create new poll - failed
voting error

**Comment by CedrikNikita** [comment]
> Pin content to channel - pass
> Search - pass
> Change currency - pass
> Account info - pass
> Change profile info (Gear button) - failed/ not active
> Comments - pass
> Retip - pass (on the mainnet)/ failed (on the testnet)
> Tip on the feed - pass (on the mainnet)/ failed (on the testnet)
> Login with Web Wallet button - failed/not active
> Voting - create a new poll - pass
> Vote - pass
> Revoke vote - pass
> Search - pass
> Meet - pass
> League - pass
> FAQ - pass
> 
> Btw, when I created a new poll to vote, there was strange behaviour:
> 
> create new poll - failed
> voting error

Broken stuff from this review were fixed in https://github.com/aeternity/superhero-ui/pull/985

**Comment by Liubov-crypto** [comment]
Pin/Unpin content to channel - pass 
Report content - pass 
Claim content - pass
Search - pass 
Change currency - pass 
Account info - pass 
Change profile info (Gear button) - pass 
Cookie policy - pass 
Comments - pass 
Post without tipping - pass 
Retip - pass 
Tip on the feed - pass 
Login with Web Wallet button - pass 
Voting:
Create a new poll - pass 
Vote - pass 
Revoke vote - pass 
Search - pass 
Meet - pass 
League - pass
FAQ - pass

I think it’s not related to this pr, but .chain name is not displayed on the feed:
chain nanme

The white stripe in FF: 
white stripe in FF

After I created poll got this warning:
poll warning

**Comment by thepiwo** [comment]
@Liubov-crypto the thing in governance is normal for, its a known issue

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto the thing in governance is normal for, its a known issue

ok, got it.

**Comment by mradkov** [comment]
@CedrikNikita can you resolve conflicts?

**Review by thepiwo — APPROVED** [review]

**Review by mradkov — APPROVED** [review]

**Pull request merged**
