### PR TITLE
Refactor MessageInput and SendComment

### PR DESCRIPTION
**Pull request by davidyuk**
refactor stuff made in #796

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
My comment was placed between old, not at the end of the comment line. It seems not correct. 
Знімок екрана 2020-11-09 о 4 41 17 пп
Also, the last 2 comments were placed incorrectly...
Знімок екрана 2020-11-09 о 4 38 15 пп

https://feature-refactor-send-comment.aggregator.z52da5wt.xyz/tip/1375_v1
As I understand it - in the comment line, the latest comment is the newest. 
Correct me if I'm wrong.

**Comment by davidyuk** [comment]
That comment placed the same as on the develop branch:

Screenshot 2020-11-10 at 21 46 48
Screenshot 2020-11-10 at 21 46 42

But it is in the right place in #864 that is approved by you, but is not merged yet :(

Screenshot 2020-11-10 at 21 46 35

Probably the only thing that this PR may break is the layout of MessageInput and SendComment components.

**Comment by Liubov-crypto** [comment]
> Probably the only thing that this PR may break is the layout of MessageInput and SendComment components, but not the ordering in the list of comments.

In that case, everything is ok.

**Review by CedrikNikita — APPROVED** [review]
Code looks ok

**Review by mradkov — APPROVED** [review]

**Pull request merged**
