### PR TITLE
SendTip: Remove extra submit handler

### PR DESCRIPTION
**Pull request by davidyuk**
Fixes duplicate form submission in Firefox. https://youtu.be/uYNLUh2rDI4

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
I tested this PR, works fine now.

**Review by Liubov-crypto — APPROVED** [review]
I tested this PR, works fine now.

**Review by CedrikNikita — APPROVED** [review]
Changes looks reasonable

**Review by mradkov — APPROVED** [review]
Good catch!

**Pull request merged**
