### PR TITLE
Add meet icon for meet menu item

### PR DESCRIPTION
**Pull request by shapkarin**
Add icon for meet menu item

### CODE REVIEW

**Comment by shapkarin** [comment]
OK. I will figure out with my Adobe XD installation and next maybe convert it with svgo also.

**Comment by mradkov** [comment]
Screenshot 2020-07-07 at 12 37 23

**Comment by shapkarin** [comment]
it's because of the way how I export from the XD or maybe because of new design, all menu icons are bigger now. I will try to do that with XD somehow to fit it.

**Comment by shapkarin** [comment]
BTW I added the svgo task, it may help to reduce the sizes, I just need to make it leave the classNames and ids and other arrtibutes.

**Comment by mradkov** [comment]
Just fix it with css.

> it's because of the way how I export from the XD or maybe because of new design, all menu icons are bigger now. I will try to do that with XD somehow to fit it.

**Comment by shapkarin** [comment]
OK

**Pull request merged**
