### PR TITLE
Show several popups using popperjs

### PR DESCRIPTION
**Pull request by davidyuk**
depends on #1138 

Extracting into separate components:
- UserPopup (Popperjs that used in Bootstrap makes it drop up if no space at the bottom, see screenshot)
- FeedItemMenu (extracts some logic from TipRecord)
- TokenSelect popup (makes to use the same component in 3 places, @onvisions is it a design requirement for them to be different?)
- TipInputPopup (extracts some logic from TipInput that is not used in deeplink use case)
- CookiesDialog

Screenshot 2021-07-09 at 21 24 51

@Liubov-crypto please ensure that mentioned components work correctly

### CODE REVIEW

**Comment by AtanasKrondev** [comment]
There's some weird flicker on the cookies popup while you are scrolling.

flick

**Comment by davidyuk** [comment]
@AtanasKrondev I've fixed it by disabling a popper plugin that is enabled by default

**Review by AtanasKrondev — APPROVED** [review]
Nice!

**Review by Liubov-crypto — COMMENTED** [review]
Tested, in general LGTM.

**Comment by davidyuk** [comment]
> The wallet seems to have a broken dropdown (scroll doesn't work), I see fewer tokens than the dropdown below the post

cc: @etharner

**Comment by davidyuk** [comment]
I've fixed TokenSelector by adding space between token name and amount

**Pull request merged**
