### PR TITLE
Release 0.5.1

### PR DESCRIPTION
**Pull request by AtanasKrondev**

### CODE REVIEW

**Review by kenodressel — CHANGES_REQUESTED** [review]
Could you bump the version number 0.5.1 in the `package.json`

**Comment by Liubov-crypto** [comment]
My profile:
Edit profile info- pass
Change pictures - pass
Cookie policy - pass
Feed:
Pin/Unpin - pass
Report post - pass
Claim post - pass
Comments - pass
Tip comment -  The transaction is processing very slowly and has not been completed
Tip on the feed - pass
Retip content on the feed - pass
Post without tipping - pass
Voting: All transactions are being processed very slowly and have not been completed.
Meet - pass
Updates - pass
FAQ - pass

**Review by kenodressel — APPROVED** [review]
thanks for the testing @Liubov-crypto

**Comment by Liubov-crypto** [comment]
> thanks for the testing @Liubov-crypto

you are welcome!

**Pull request merged**
