### PR TITLE
wordbazaar testnet placeholder

### PR DESCRIPTION
**Pull request by thepiwo**

### CODE REVIEW

**Comment by mradkov** [comment]
Should we also have the build procedure both testnet and mainnet?

**Comment by thepiwo** [comment]
@mradkov for now its fine if we cherry pick this commit if we want to have an example testnet deploy

**Comment by gorbak25** [comment]
image
:heart:

**Comment by gorbak25** [comment]
image
:thinking:

**Comment by thepiwo** [comment]
@gorbak25 was just the wrong contract used, should be working now

**Comment by gorbak25** [comment]
@thepiwo Works great :)

**Comment by thepiwo** [comment]
@AtanasKrondev can we use this just as testnet placeholder for the env and make logical/design changes in separate PRs?

**Pull request closed without merging**
