### PR TITLE
chore: update SDK to 8.1.0

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
The new UI and old wallet works well for me. 
New UI + old wallet: 
Connection after accepting pop-ups - pass
Search results - pass
Delete/ update avatar - pass
Update profile info - pass
Cookie policy - pass
Comment on the feed - pass
Report post - pass
Pin content to channel - pass
Post no the feed without tipping gif/pic- pass
Send tip on the feed - pass
Retip on the feed - pass
Claim tip on the feed - pass
Voting: 
Vote - pass
Revoke vote - pass
Delegate voting power - pass
Search - pass
Create a poll - pass
Meet - pass
Updates - pass
FAQ - pass

If I search for the word "pool" and I get results with the word "cool", is that okay? these words have common letters "ool'.

**Comment by Liubov-crypto** [comment]
Currently, there is no connection between sh wallet (21cc06b pr 1045) and sh UI. 
The wallet does not see the pop-ups, to accept them and establish a connection.

**Comment by davidyuk** [comment]
> If I search for the word "pool" and I get results with the word "cool", is that okay? these words have common letters "ool'.

I think yes. Probably backend uses some fuzzy search algorithm. cc: @kenodressel 

> there is no connection between sh wallet

this should be fixed on the wallet side

**Comment by Liubov-crypto** [comment]
> > If I search for the word "pool" and I get results with the word "cool", is that okay? these words have common letters "ool'.
> 
> I think yes. Probably backend uses some fuzzy search algorithm. cc: @kenodressel
> 
> > there is no connection between sh wallet
> 
> this should be fixed on the wallet side

Retested, LGTM. 
Comments and transactions appear a little late, but maybe it's an internet connection or backend.

**Comment by thepiwo** [comment]
will you update to beta.2? when will we merge that?

**Review by thepiwo — COMMENTED** [review]
can we update to latest sdk and merge?

**Review by mradkov — APPROVED** [review]

**Pull request merged**
