### PR TITLE
Feature/ssr combine

### PR DESCRIPTION
**Pull request by shapkarin**
Maybe we can revert the `import store from '../store';` at the `src/utils/backend.js` 

This PR is the combination of several others PRs.

### CODE REVIEW

**Comment by mradkov** [comment]
`(node:62405) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined`

**Comment by shapkarin** [comment]
todo: remove work with error handling from this PR and save it at other branch https://github.com/aeternity/superhero-ui/tree/feature/maintance_handler

**Comment by venimus** [comment]
After refresh or reopening I start seeing this error message which breaks the future rendering and navigation
image
I found that after deleting the vuex stored data it starts working again until the next refresh

**Comment by shapkarin** [comment]
@venimus what page did you refresh and reopen?

**Comment by venimus** [comment]
> @venimus what page did you refresh and reopen?

any page

**Comment by shapkarin** [comment]
@venimus thanks. I see, you use build and next `npm run ssr:start`

**Comment by davidyuk** [comment]
@IvayloPapazov SSH access seems to be broken on SSR server, can you check it?

**Comment by davidyuk** [comment]
some of these were merged before, other parts implemented in #1116 and #908, so closing this one

**Pull request closed without merging**
