### PR TITLE
Enable account switching

### PR DESCRIPTION
**Pull request by CedrikNikita**
can be tested with https://github.com/aeternity/superhero-wallet/pull/1043

### CODE REVIEW

**Review by thepiwo — APPROVED** [review]
code looks good, didn't test it

**Comment by kenodressel** [comment]
Should we merge this? @CedrikNikita

**Comment by kenodressel** [comment]
@Liubov-crypto could you test this please?

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto could you test this please?

sure

**Comment by Liubov-crypto** [comment]
My profile: 
Edit profile info- pass 
Change pictures - pass 
Cookie policy - pass  
Feed:
Pin/Unpin - pass 
Report post - pass 
Claim post - pass (got modals)
Comments - pass 
Tip comment -  The transaction is processing very slowly and has not been completed
Tip on the feed - The transaction is processing very slowly and has not been completed
Retip content on the feed - The transaction is processing very slowly and has not been completed
Post without tipping - The transaction is processing very slowly and has not been completed
Voting: All transactions are being processed very slowly and have not been completed.
Meet - pass 
Updates - pass 
FAQ - pass 

I can't complete the transactions described above because microblocks are packed very slowly and all my transactions are still pending:
transactions

**Pull request merged**
