### PR TITLE
Don't make wallet initialisation depend on backend fetching and related refactoring

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Review by mradkov — APPROVED** [review]
Looks good.

**Review by mradkov — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
For a long time, My Profile on superhero ui did not appear when I logged in with an extension. I need to refresh the page several times and after that my profile will become visible in the superhero ui.

When I logged in with an I-frame wallet, the wallet itself took a very long time to load and was inaccessible (black), but maybe this is an internet connection. The wallet overloads itself several times during my testing.
Знімок екрана 2020-10-28 о 3 53 16 пп


if you tip at the top of the supehero ui, then the pop-up appears 2 times, the tip itself is successful, then a pop-up appears that the operation is not successful, but the tip appears in the feed.

Знімок екрана 2020-10-28 о 4 01 03 пп

**Comment by mradkov** [comment]
> For a long time, My Profile on superhero ui did not appear when I logged in with an extension. I need to refresh the page several times and after that my profile will become visible in the superhero ui.
> 
> When I logged in with an I-frame wallet, the wallet itself took a very long time to load and was inaccessible (black), but maybe this is an internet connection. The wallet overloads itself several times during my testing.
> Знімок екрана 2020-10-28 о 3 53 16 пп
> 
> if you tip at the top of the supehero ui, then the pop-up appears 2 times, the tip itself is successful, then a pop-up appears that the operation is not successful, but the tip appears in the feed.
> 
> Знімок екрана 2020-10-28 о 4 01 03 пп

Strange. For me, it works smoothly - logging with the wallet. (I havent tested tipping as it should not be changed actually).

**Comment by Liubov-crypto** [comment]
> Strange. For me, it works smoothly - logging with the wallet. (I havent tested tipping as it should not be changed actually).

I checked all the important functions, tip, comment, as requested by Denis.

**Comment by mradkov** [comment]
This button is visible for 5-6seconds before I see the screen for generating a wallet. I think we need to think of a better UX.

Screenshot 2020-10-29 at 20 23 09

**Comment by davidyuk** [comment]
@Liubov-crypto for some reason I can't reproduce the issues you mentioned, I have even tried to leave a tip. If it is still reproducible, I'm proposing to show it in a call.

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto for some reason I can't reproduce the issues you mentioned, I have even tried to leave a tip. If it is still reproducible, I'm proposing to show it in a call.

@davidyuk On my side, this issue is still reproducible. I recorded a video: https://youtu.be/uYNLUh2rDI4

Used this link for testing: https://feature-refactor-wallet-connection.aggregator.z52da5wt.xyz/ 
and extension Superhero 867f0d7 / v.0.3.3 

sure, we can arrange a call

**Comment by davidyuk** [comment]
That was in Firefox, ok, I have reproduced it. But it also occurs on the develop branch, so it is not related to this PR, I have fixed it in #875

**Comment by Liubov-crypto** [comment]
> That was in Firefox, ok, I have reproduced it. But it also occurs on the develop branch, so it is not related to this PR, I have fixed it in #875.
> 
> @Liubov-crypto are there any bugs introduced by this PR?

During my testing, the tipping bug on the superhero feed repeated. Although tip itself was successful, an inscription appears that it was unsuccessful. 
Знімок екрана 2020-11-09 о 12 57 53 пп

I recorded a video: https://youtu.be/65BdMnxrFAU

Browser: Chrome, 
Wallet: Superhero ed188a8 / v.0.3.3 

I did not observe such an error in FF and Brave.

**Comment by davidyuk** [comment]
I have rebased it on the top of develop branch.

**Review by CedrikNikita — APPROVED** [review]
Changes look reasonable

**Pull request merged**
