### PR TITLE
aepps integration

### PR DESCRIPTION
**Pull request by pseudozach**
Hi, this PR is opened as part of aeppstore project per milestone-3 of the grant (https://forum.aeternity.com/t/active-aepp-store-fast-easy-aepp-discovery/9494)

### CODE REVIEW

**Comment by pseudozach** [comment]
Hi, can you please review this PR and let me know if it's feasible? Or any issues with it?

**Comment by kenodressel** [comment]
Are you committed to maintaining this?

**Comment by ErkanKanden** [comment]
It is mentioned in the original Foundation grant application that @pseudozach will maintain this for one year: https://forum.aeternity.com/t/active-aepp-store-fast-easy-aepp-discovery/9494

**Comment by kenodressel** [comment]
- Could you please make a commit that adheres to the https://www.conventionalcommits.org/en/v1.0.0/ standard
- make sure the ci passes (at least the test, build & deploy part)

thanks :)

**Comment by kenodressel** [comment]
any update @pseudozach?

**Comment by pseudozach** [comment]
> any update @pseudozach?

hi, I'm blocked waiting for a payment from the foundation. Once that comes through I'll follow up. thanks and sorry for the delay.

**Comment by pseudozach** [comment]
@kenodressel please take another look. I've added a new commit with requested syntax.
I've checked and both ci and test are passing.

**Comment by kenodressel** [comment]
I don't see any new commits in this PR.

**Comment by kenodressel** [comment]
I guess part of your problem is that the first PR is not adhering to the conventional commit standard. Please fix this. An example can be found here: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message

**Comment by pseudozach** [comment]
how about now? is this better?

**Comment by kenodressel** [comment]
hm this seems weird, there are now some commits on your branch that should not be there (from Nikita Cedrik).

**Pull request closed without merging**
