### PR TITLE
Do not display scrollbars in dropdowns - Firefox

### LINKED ISSUE #1076: White stripe in FF browser
The white stripe in FF when changing tokens:
white stripe in FF
white stripe in ff1
white stripes tokens tab

and in Meet:
white stripe FF meet

Also reproduced on product version 54b729c / 0.4.2

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Fixes #1076

### CODE REVIEW

**Review by Liubov-crypto — COMMENTED** [review]
If I click on the dropdown menu on iframe wallet or trending the white stripe in Meet becomes visible:

https://user-images.githubusercontent.com/69896204/118667494-bcac9280-b7fc-11eb-85b7-7b336eade2bf.mov

also with extension in Meet:
FF ws

The dropdown menu with currencies looks good.

**Comment by Liubov-crypto** [comment]
The white stripe remains in the Meet.
The product version looks good, but if I reload the page, then a white stripe appears:
https://user-images.githubusercontent.com/69896204/120310400-05754880-c2df-11eb-9374-2aa57081f74a.mov

**Comment by kenodressel** [comment]
@AtanasKrondev whats the state here?

**Comment by AtanasKrondev** [comment]
> @AtanasKrondev whats the state here?

The scrollbar in the Meet tab is inside the iframe so not much more to do.
It can be merged.

**Review by kenodressel — APPROVED** [review]

**Pull request merged**
