### PR TITLE
Remove custom timeout exception generator

### PR DESCRIPTION
**Pull request by davidyuk**
We have issues with custom timeouts, I'm proposing to remove them. Was there any specific reason for them? As I know, HTTP has native timeouts and they should work ok.

### CODE REVIEW

**Comment by mradkov** [comment]
This was the reason. https://github.com/aeternity/superhero-ui/pull/798#issue-483750940

**Comment by davidyuk** [comment]
It doesn't look like a reason, more like an adjustment of custom timeout introduced before. But why this timeout was introduced?

**Comment by mradkov** [comment]
As the backend is fetching and caching the data from the smart contract it took ~3-4 sec to have its cache reloaded and updated. So initially this was implemented for that reason so the backend has time to update the cache before we reload the page. 🤔

**Comment by thepiwo** [comment]
the timeouts were there to prevent blocking of frontend loading in case the backend is slow, but as we now depend much more on the backend this is maybe not required any more

**Comment by davidyuk** [comment]
@mradkov I'm not proposing to remove the delay introduced in #798 

The thing is that in some cases it breaks crucial stuff
Wire 2020-10-06 at 6_06 PM
Wire 2020-10-06 at 6_08 PM

**Comment by davidyuk** [comment]
the same change got merged in #825, so closing this one

**Pull request closed without merging**
